declare module '*.module.css';
declare module '*.css';
declare module 'react-router-dom'
declare module 'formik'
declare module "*.png";
declare module "*.svg";
declare module "*.jpg";
declare module "*.jpeg"; 
declare module "*.gif"; 