export const GET_ANIMES = "GET_ANIMES";
export const SEARCH_ANIMES = "SEARCH_ANIMES";
export const GET_ANIME_BY_ID = 'GET_ANIME_BY_ID';
export const GET_ANIME_EPISODES = 'GET_ANIME_EPISODES';
export const FILTER_AND_SORT_ANIMES = 'FILTER_AND_SORT_ANIMES';
export const GET_ANIME_GENRES = 'GET_ANIME_GENRES';